### PR TITLE
fix(deps): update dependencies for release 7.1

### PR DESCRIPTION
**Pull request by ThibaultRiviere**

### CODE REVIEW

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
It looks like ultron doesn't have the branch `rel/7.1` lol

**Comment by philipyoo** [comment]
Will these updates also include node version update? `"node": ">=6.9.5"`

**Comment by ThibaultRiviere** [comment]
@philipyoo  Actually i'm not a big fan of this. I like to keep version static in purpose to avoid any breaking change. Specially when our CI is using a specific version of node and doesn't test all the version `>= 6.9.5`
If the decision is to go for it, i will create an other PR .
This change is not related to the branching models we use for our release

**Comment by ThibaultRiviere** [comment]
@ironman-machine r+

**Comment by ThibaultRiviere** [comment]
retried here : http://ci.ironmann.io/gh/scality/Integration/14852#build-parameters

**Pull request merged**
