### PR TITLE
bf: make getRaftLog() return a stream

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Instead of returning a data blob, return the stream sent by the server
to manage memory better and avoid issues with toString() when blob is
too large.

### CODE REVIEW

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_ARSENAL_BRANCH=bf/S3C-1134-streamLogConsumer
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=bf/S3C-1134-streamLogConsumer
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=bf/S3C-1134-streamLogConsumer
SCALITY_METADATA_BRANCH=bf/S3C-1134-streamLogConsumer
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=bf/S3C-1134-streamLogConsumer
SCALITY_METADATA_BRANCH=bf/S3C-1134-streamGetRaftLog
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=bf/S3C-1134-streamLogConsumer
SCALITY_METADATA_BRANCH=bf/S3C-1134-streamGetRaftLog
try

**Comment by jonathan-gramain** [comment]
@ironman-machine
SCALITY_ARSENAL_BRANCH=bf/S3C-1134-streamLogConsumer
SCALITY_METADATA_BRANCH=bf/S3C-1134-streamGetRaftLog
try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by jonathan-gramain** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by jonathan-gramain** [comment]
https://github.com/scality/Integration/pull/618

This PR will hopefully help reduce observed flakiness

**Comment by jonathan-gramain** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
Retry after rebase of Arsenal branch onto rel/7.2.
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine try
SCALITY_BACKBEAT_BRANCH=tmp/event-listener-debug
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=tmp/event-listener-debug
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=tmp/remove-all-listeners-debug
try

**Comment by rahulreddy** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=fix/S3C-1134
try

**Comment by rahulreddy** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=tmp/remove-all-listeners-debug
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=fix/S3C-1134
try

Once more to obtain artifacts.

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=tmp/event-listener-debug
try

**Comment by rahulreddy** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=tmp/event-listener-debug
try

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_BACKBEAT_BRANCH=fix/S3C-1134
try

**Comment by jonathan-gramain** [comment]
@ironman-machine 
SCALITY_BACKBEAT_BRANCH=bf/S3C-1134-streamLogConsumer
try

**Comment by jonathan-gramain** [comment]
@ironman-machine try

**Comment by jonathan-gramain** [comment]
Integration passed in http://ci.ironmann.io/gh/scality/Integration/18729

A new PR is required in backbeat: https://github.com/scality/backbeat/pull/169 (can be merged by itself first once tests pass).

**Comment by rahulreddy** [comment]
@ironman-machine 
clean
after=https://github.com/scality/Arsenal/pull/379
r+

**Comment by rahulreddy** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Pull request merged**
