### PR TITLE
PERF: improvment

### PR DESCRIPTION
**Pull request by alexandre-merle**
- Allow api call to use the same request
  logger instead of create a new one for
  each request

### CODE REVIEW

**Comment by ThibaultRiviere** [comment]
:+1:

**Comment by michael-zapata** [comment]
Mh, this defeats the purpose of the request logging. Is that something desired?

**Comment by alexandre-merle** [comment]
Why ? This is not really a priority, the most improvement is in vaultclient, but this one save also s3 cpu usage, because for each request of s3 we create a logger each time we use a bucketclient method :)

**Comment by michael-zapata** [comment]
We did want clear boundaries between components, that's why we passed the uids rather than the full-fledged logger. I do agree that passing the object directly is a better idea though.

**Comment by MathieuCassagne** [comment]
:+1:

**Comment by alexandre-merle** [comment]
Dropme removed :)

**Comment by ThibaultRiviere** [comment]
@ironman-machine  can i merge that ?

**Pull request merged**
