### PR TITLE
improvement: BKCLT-3 update deps and yarn lock

### PR DESCRIPTION
**Pull request by naren-rajendran**

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e force_reset

**Comment by naren-rajendran** [comment]
@bert-e ping

**Comment by naren-rajendran** [comment]
@bert-e approve

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e force_reset

**Comment by naren-rajendran** [comment]
@bert-e ping

**Comment by naren-rajendran** [comment]
@bert-e force_reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Review by tcarmet — APPROVED** [review]

**Pull request merged**
