### PR TITLE
Fwdport 6.3 to 6.4

### PR DESCRIPTION
**Pull request by ThibaultRiviere**

### CODE REVIEW

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
@ironman-machine try

**Comment by ThibaultRiviere** [comment]
This PR have lot of conflicts be careful. 
Need to be tested with scality/Federation#852

**Comment by DavidPineauScality** [comment]
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
Network flaky...
@ironman-machine r- r+

**Comment by DavidPineauScality** [comment]
@vrancurel related to our ongoing fixes of ports configuration.

**Pull request merged**
