### PR TITLE
Chore: upgrade eslint

### PR DESCRIPTION
**Pull request by philipyoo**
List of Eslint rules: https://eslint.org/docs/rules/

Note: Will squash commits after making any changes based on peoples' feedback

### CODE REVIEW

**Comment by philipyoo** [comment]
@ironman-machine try

**Comment by philipyoo** [comment]
e2e auto-retried here: http://ci.ironmann.io/gh/scality/Integration/15007

**Comment by ThibaultRiviere** [comment]
@ironman-machine r+

**Comment by philipyoo** [comment]
thank you @ThibaultRiviere ! :)

**Pull request merged**
