### PR TITLE
Improvement/s3 c 2358 migrate package manager to yarn

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Migrate package manager to yarn

**Which issue does this PR fix?**
fixes #S3C-2358

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
test

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Review by rahulreddy — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Review by jonathan-gramain — APPROVED** [review]

**Review by vrancurel — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Comment by rahulreddy** [comment]
@bert-e bypass_peer_approval

**Review by vrancurel — APPROVED** [review]

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Pull request merged**
