### PR TITLE
Fwdport 6.2 to 6.2.1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
E2E launched globally from https://github.com/scality/Integration/pull/287

**Comment by DavidPineauScality** [comment]
Not merging this one for now, due to its potential relationship with scality/Metadata#733
I'll leave this for @ThibaultRiviere to manage with the associated MD PR.

**Comment by DavidPineauScality** [comment]
MErging on behalf of @ThibaultRiviere (Tests launched from https://github.com/scality/Integration/pull/289, and are passing in a retry (build 5804))

**Review by MathieuCassagne — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Lgtm.

**Review by ThibaultRiviere — APPROVED** [review]

**Comment by ThibaultRiviere** [comment]
@ironman-machine

**Pull request merged**
